
const wordList = ['DOG', 'APPLE', 'TREE', 'RIVER'];

// ["CROYDON", "MILSONS POINT", "LAVENDER BAY", "SYDNEY", "KIRRIBILLI", "CAMPERDOWN", "PADDINGTON", "NEWTOWN", "MANLY", "BALMAIN", "GLEBE", "CRONULLA", "SURRY HILLS", "POTTS POINT", "WOLLOOMOOLOO", "RANDWICK"]